// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Test1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void test1() {
    driver.Navigate().GoToUrl("https://www.google.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1382, 754);
    driver.FindElement(By.Name("q")).Click();
    driver.FindElement(By.Name("q")).SendKeys("QA automation video");
    driver.FindElement(By.Name("q")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("rcnt")).Click();
    driver.FindElement(By.Id("res")).Click();
    driver.FindElement(By.Id("res")).Click();
    Assert.That(driver.FindElement(By.CssSelector(".bkWMgd > .g > div > .rc .LC20lb")).Text, Is.EqualTo("Automation Testing Tutorial for Beginners - YouTube"));
    driver.Close();
  }
}
